site_name: Zakiullah Khan
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
