site_name: Zakiullah Khan
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.share
plugins:
  - search
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  analytics:
    provider: google
    property: G-G2W4V6PSJE
