site_name: Zakiullah Khan
site_author: Zakiullah Khan <simplyzaki@outlook.com>
site_url: http://www.simplyzaki.com
copyright: Copyright 2023 Zakiullah Khan
theme:
  name: material
  language: en
  direction: ltr
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - tags
  - search
  - offline
  - social
  - blog:
      blog_dir: .
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  analytics:
    provider: google
    property: G-G2W4V6PSJE
  consent:
    title: Cookie consent
    description: >- 
      My blog uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my content and whether users
      find what they're searching for. With your consent, you're helping us to
      make my blog better.
nav:
  - index.md
